[versions]
androidxConstraintlayout = "2.2.1"
androidxNavigation = "2.9.6"
comAndroid = "9.0.0"
comGoogleAndroidMaterial = "1.13.0"
comGoogleCodeGson = "2.13.2"
comInnovatricsDot = "9.1.0"
devKeijiJp2Android = "1.0.5"
orgJlleitschuhGradleKtlint = "14.0.1"

[libraries]
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintlayout" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidxNavigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidxNavigation" }
com-google-android-material = { group = "com.google.android.material", name = "material", version.ref = "comGoogleAndroidMaterial" }
com-google-code-gson = { module = "com.google.code.gson:gson", version.ref = "comGoogleCodeGson" }
com-innovatrics-dot-document = { group = "com.innovatrics.dot", name = "dot-document", version.ref = "comInnovatricsDot" }
com-innovatrics-dot-face-detection-fast = { group = "com.innovatrics.dot", name = "dot-face-detection-fast", version.ref = "comInnovatricsDot" }
com-innovatrics-dot-face-expression-neutral = { group = "com.innovatrics.dot", name = "dot-face-expression-neutral", version.ref = "comInnovatricsDot" }
com-innovatrics-dot-nfc = { group = "com.innovatrics.dot", name = "dot-nfc", version.ref = "comInnovatricsDot" }
com-innovatrics-dot-palm-detection = { group = "com.innovatrics.dot", name = "dot-palm-detection", version.ref = "comInnovatricsDot" }
dev-keiji-jp2-android = { group = "dev.keiji.jp2", name = "jp2-android", version.ref = "devKeijiJp2Android" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "comAndroid" }
org-jlleitschuh-gradle-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "orgJlleitschuhGradleKtlint" }
